#!/bin/bash

(
    cd crossbuilder
    # Remove go.mod and go.sum to avoid conflicts with the parent go.mod and go.sum
    rm go.mod go.sum

    go mod tidy
    echo "building xrc-gen"
    go build -trimpath -o bin/xrc-gen cmd/xrc-gen/main.go

    echo "building xrd-gen"
    go build -trimpath -o bin/xrd-gen cmd/xrd-gen/main.go
)

./crossbuilder/bin/xrc-gen

# Put go.mod and go.sum back to the original state
(
    cd crossbuilder
    git checkout -- go.mod go.sum
)

# Put go.mod and go.sum back to the original state on the parent directory
go mod tidy