#!/bin/bash
go mod tidy
go build -trimpath -o xrc-gen ./cmd/xrc-gen
export PATH=$PATH:$(pwd)

cd $(dirname $(find . -maxdepth 2 -type d -name compositions))

echo "copying go.mod and go.sum"
cp /crossbuilder/go.* .

echo "generating compositions"
xrc-gen

echo "generating definitions"
go generate ./...
rm go.*